const roles = {
  'Grumete Novato V 👶': 0,
  'Grumete Novato IV 👶': 2,
  'Grumete Novato III 👶': 4,
  'Grumete Novato II 👶': 6,
  'Grumete Novato I 👶': 8,
  'Aprendiz de Navegante V 🗺️': 10,
  'Aprendiz de Navegante IV 🗺️': 12,
  'Aprendiz de Navegante III 🗺️': 14,
  'Aprendiz de Navegante II 🗺️': 16,
  'Aprendiz de Navegante I 🗺️': 18,
  'Compañero de Tripulación V ⚓': 20,
  'Compañero de Tripulación IV ⚓': 22,
  'Compañero de Tripulación III ⚓': 24,
  'Compañero de Tripulación II ⚓': 26,
  'Compañero de Tripulación I ⚓': 28,
  'Guerrero del Mar V ⚔️': 30,
  'Guerrero del Mar IV ⚔️': 32,
  'Guerrero del Mar III ⚔️': 34,
  'Guerrero del Mar II ⚔️': 36,
  'Cazador de Recompensas III 🎯': 44,
  'Cazador de Recompensas II 🎯': 46,
  'Cazador de Recompensas I 🎯': 48,
  'Capitán de Barco V 🚢': 50,
  'Capitán de Barco IV 🚢': 52,
  'Capitán de Barco III 🚢': 54,
  'Capitán de Barco II 🚢': 56,
  'Capitán de Barco I 🚢': 58,
  'Maestro del Haki V 🥋': 60,
  'Maestro del Haki IV 🥋': 62,
  'Maestro del Haki III 🥋': 64,
  'Maestro del Haki II 🥋': 66,
  'Maestro del Haki I 🥋': 68,
  'Almirante Legendario V 🔱': 70,
  'Almirante Legendario IV 🔱': 72,
  'Almirante Legendario III 🔱': 74,
  'Almirante Legendario II 🔱': 76,
  'Almirante Legendario I 🔱': 78,
  'Maestro de las Frutas del Diablo V 🍎': 80,
  'Maestro de las Frutas del Diablo IV 🍎': 85,
  'Maestro de las Frutas del Diablo III 🍎': 90,
  'Maestro de las Frutas del Diablo II 🍎': 95,
  'Maestro de las Frutas del Diablo I 🍎': 99,
  'Yonko de Élite V 👑': 100,
  'Yonko de Élite IV 👑': 110,
  'Yonko de Élite III 👑': 120,
  'Yonko de Élite II 👑': 130,
  'Yonko de Élite I 👑': 140,
  'Emperador del Mar V 🌊': 150,
  'Emperador del Mar IV 🌊': 160,
  'Emperador del Mar III 🌊': 170,
  'Emperador del Mar II 🌊': 180,
  'Emperador del Mar I 🌊': 199,
  'Rey Pirata': 200,
  'Rey Pirata IV 🥇': 225,
  'Rey Pirata III 🥇': 250,
  'Rey Pirata II 🥇': 275,
  'Rey Pirata I 🥇': 299,
  'Dios de la Aventura V 🌟': 300,
  'Dios de la Aventura IV 🌟': 325,
  'Dios de la Aventura III 🌟': 350,
  'Dios de la Aventura II 🌟': 375,
  'Dios de la Aventura I 🌟': 399,
  'Leyenda del Grand Line V 📜': 400,
  'Leyenda del Grand Line IV 📜': 425,
  'Leyenda del Grand Line III 📜': 450,
  'Leyenda del Grand Line II 📜': 475,
  'Leyenda del Grand Line I 📜': 499,
  'Pirata Inmortal V ♾️': 500,
  'Pirata Inmortal IV ♾️': 525,
  'Pirata Inmortal III ♾️': 550,
  'Pirata Inmortal II ♾️': 575,
  'Pirata Inmortal I ♾️': 599,
  'Deidad del Mar V 🌌': 600,
  'Deidad del Mar IV 🌌': 625,
  'Deidad del Mar III 🌌': 650,
  'Deidad del Mar II 🌌': 675,
  'Deidad del Mar I 🌌': 699,
  'Gigante del Mar V 🏔️': 700,
  'Gigante del Mar IV 🏔️': 725,
  'Gigante del Mar III 🏔️': 750,
  'Gigante del Mar II 🏔️': 775,
  'Gigante del Mar I 🏔️': 799,
  'Sabio de los Océanos V 🦉': 800,
  'Sabio de los Océanos IV 🦉': 825,
  'Sabio de los Océanos III 🦉': 850,
  'Sabio de los Océanos II 🦉': 875,
  'Sabio de los Océanos I 🦉': 899,
  'Viajero Dimensional V 🌠': 900,
  'Viajero Dimensional IV 🌠': 925,
  'Viajero Dimensional III 🌠': 950,
  'Viajero Dimensional II 🌠': 975,
  'Viajero Dimensional I 🌠': 999,
  '🌟 Dios Supremo del Mar 🌟': 1000,
  '🌟 Dios Supremo del Mar II 🌟': 2000,
  '🌟 Dios Supremo del Mar III 🌟': 3000,
  '🌟 Dios Supremo del Mar IV 🌟': 4000,
  '🌟 Dios Supremo del Mar V 🌟': 5000,
  '👑 Gran Héroe de los Mares 👑': 10000
}